version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: Postgres_mydb
    restart: always
    environment:
      - POSTGRES_USER=postgres_uzer
      - POSTGRES-PASSWORD=postgres_pass_777
    ports:
    - '5432:5432'
    volumes:
    - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local
